# Initial content coming from
# https://github.com/pre-commit/pre-commit-hooks/blob/master/.pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml

# end
